trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '13.x'
            displayName: 'Install Node.js'

          - task: YarnInstaller@3
            inputs:
              versionSpec: '1.x'
            displayName: 'Install Yarn'

          - script: |
              yarn install
              yarn build
            displayName: 'Yarn install and build'

          - publish: $(System.DefaultWorkingDirectory)/build
            artifact: NukeBot
            displayName: 'Publish Artifacts'

  - stage: DeployProd
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    displayName: 'Deploy Production'
    dependsOn: Build
    jobs:
      - job: DeployProduction
        steps:
          - download: current
            artifact: NukeBot
            displayName: 'Download Artifacts'
              
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'Nighthawk'
              sourceFolder: '$(Pipeline.Workspace)/NukeBot'
              contents: 'index.js'
              targetFolder: $(TargetFolder)
            displayName: 'Copy files to server'

          - task: SSH@0
            inputs:
              sshEndpoint: 'Nighthawk'
              runOptions: 'commands'
              commands: |
                sudo chown discord $(TargetFolder)/index.js
                sudo systemctl restart discord-bot
            displayName: 'Restart bot service'